
# retornar dados no grid

@hostname=localhost
@port=5000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjg0MTgyNTUyLCJleHAiOjE2ODQ3ODczNTJ9.3I0LSmmDaR8NmpLZW3o6zpplHpntPwAO2vFf6oPgwoY
###
POST  http://{{hostname}}:{{port}}/api/grids/ticket
Content-Type: application/json; charset=utf-8
Authorization:Bearer {{token}}

{"idTipoCadastro":6,"page":0,"sizePage":5,"sorting":[{"columnName":"Token","direction":"asc"}],"filter":""}

###